<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>iex</string>
		<string>ex</string>
	</array>
	<key>name</key>
	<string>elixir test</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(with)\s*\"([^\"]*)\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.elixir</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.string.elixir</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\send</string>
			<key>name</key>
			<string>meta.test.elixir</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.elixir</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.elixir</string>
</dict>
</plist>
