<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>iex</string>
		<string>ex</string>
	</array>
	<key>name</key>
	<string>Elixir</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(with)\s*\"([^\"]*)\"</string>
			<key>end</key>
			<string>\sdo</string>
			<key>name</key>
			<string>meta.test.elixir</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.elixir</string>
	<key>uuid</key>
	<string>D00C06B9-71B2-4FEB-A0E3-37237F579456</string>
</dict>
</plist>
